### ISSUE TITLE
Please add NBT tag support 

### ISSUE THREAD

**Issue by S0ly** [7sat/DynamicShop3#71]
Please add nbt tag

**Comment by vjh0107** [comment]
for where? already item supports NBT tags

**Comment by S0ly** [comment]
Enchant, Potion, Egg, Damaged item, Items from other plugins support (NBT tag is not supported)

**Comment by vjh0107** [comment]
what custom items plugin are you currently using?

**Comment by S0ly** [comment]
i'm using item adder
