### ISSUE TITLE
Lore gets cut off 

### ISSUE THREAD

**Issue by catches** [7sat/DynamicShop3#81]
**Minecraft version**
1.19.3

**Plugin version**
3.9.0

**Describe the bug**
![image](https://user-images.githubusercontent.com/105005455/219931406-c153175b-b9b8-40a6-8924-3412f7b9dc60.png)
![image](https://user-images.githubusercontent.com/105005455/219931417-42da5b1b-2d06-4f98-9e38-d837d776612c.png)
![image](https://user-images.githubusercontent.com/105005455/219931424-8684d12d-d1d1-4973-af82-fd024a7b7e4d.png)
![image](https://user-images.githubusercontent.com/105005455/219931434-1c7f16bb-04c9-45c0-8c9b-cca1f29797a2.png)

**To Reproduce**
Add an item with lore

**Expected behavior**
Keeps the lore

Would also be nice if we could have more customization like adjusting the format, where it displays the item lore first, and have everything after, as well as changing around the GUI. Also possible to add player heads support from minecraftheads? Thanks!

**Comment by 7sat** [comment]
I'm checking on this issue.

**Comment by 7sat** [comment]
In the case of format, it is possible to edit even now.
example)
![image](https://user-images.githubusercontent.com/49030779/220111903-5762ecf4-7b4d-4f92-a240-56d20541d797.png)  
result)
![image](https://user-images.githubusercontent.com/49030779/220111960-2f47e6a5-9069-4458-b2d5-58590c3b288e.png)

**Comment by 7sat** [comment]
I watched for a long time to see which part of the lore was being cut. lol
I guess it's because I'm not an English-speaking person.

**Comment by 7sat** [comment]
This problem has now been fixed.
