### ISSUE TITLE
Suggestion - Allow Purchasing Commands

### ISSUE THREAD

**Issue by BirminghamBoy** [7sat/DynamicShop3#83]
Currently, DynamicShop allows purchasing of items. However, I also wish to sell 'commands' (for example, selling items from other plugins that are gained using commands; selling mcMMO experience; selling XP; etc). Currently, I am needing to use a separate plugin for this.

**Comment by 7sat** [comment]
There are no plans to directly support command sales.
However, in a recent update, the plug-in can trigger arbitrary server commands to be executed when a purchase or sale occurs.
I think you can get a similar result in an indirect way through this.

**Comment by 7sat** [comment]
I will close this issue tomorrow.
