### ISSUE TITLE
Minecraft 1.20.2 compatibility

### ISSUE THREAD

**Issue by pjindras** [7sat/DynamicShop3#93]
**Minecraft version**
1.20.2

**Plugin version**
3.15.2

**Describe the bug**
Plugin is not compatible with 1.20.2 - adding items is not possible etc.

**To Reproduce**
Try to install the plugin on paper 1.20.2

@FlorianKoerner 
@Multitallented 
@jpenilla 
@7sat

**Comment by 7sat** [comment]
https://github.com/7sat/DynamicShop3/commit/1dff0cbe9b86ebea46aa9fa345612b36c6d82b7f
